2025-04-21 16:42:14,287 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,287 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,295 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,295 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,460 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,460 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,461 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,461 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,600 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,600 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,600 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,600 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:14,602 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,602 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,602 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:14,602 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "/home/olex/.local/lib/python3.8/site-packages/flask/scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "/home/olex/.local/lib/python3.8/site-packages/flask/helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:17,741 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:17,741 - ERROR - __main__ - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-04-21 16:42:17,746 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/olex/.local/lib/python3.8/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-21 16:42:17,746 - ERROR - __main__ - Traceback: Traceback (most recent call last):
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/olex/.local/lib/python3.8/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/olex/.local/lib/python3.8/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/olex/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

